root: true
reportUnusedDisableDirectives: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 6
  sourceType: 'module'
  project:
    - './tsconfig.json'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
plugins:
  - "@typescript-eslint"
rules:
  'prefer-const':
    - 'warn'
    - destructuring: 'all'
  'no-throw-literal': 'warn'

  # typescript checks this for us
  no-undef: 'off'

  no-restricted-globals:
    - 'error'
    - name: 'SharedArrayBuffer'
      message:
        'SharedArrayBuffer is not yet implemented in all runtimes we support.  For details, see https://caniuse.pp.dropbox.com/#feat=mdn-api_JavaScript-builtins--SharedArrayBuffer'

  eqeqeq:
   - 'error'
   - 'allow-null'
