root: true
reportUnusedDisableDirectives: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 6
  sourceType: 'module'
  project:
    - './tsconfig.json'
extends:
  - 'eslint:recommended'
  - 'prettier'
rules:
  # Dropbox standard rules
  'prefer-const':
    - 'warn'
    - destructuring: 'all'
  'no-throw-literal': 'warn'
  no-restricted-globals:
    - 'error'
    - name: 'SharedArrayBuffer'
      message: 'SharedArrayBuffer is not yet implemented in all runtimes we support.  For details, see https://caniuse.pp.dropbox.com/#feat=mdn-api_JavaScript-builtins--SharedArrayBuffer'

  # TTVC rules
  eqeqeq:
    - 'error'
    - 'allow-null'
  # typescript checks this for us
  no-undef: 'off'

overrides:
  - files:
      - '*.ts'
    plugins:
      - '@typescript-eslint'
    extends:
      - 'plugin:@typescript-eslint/eslint-recommended'
      - 'plugin:@typescript-eslint/recommended'
      - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
